[package]
name = "xr3wm"
version = "0.1.0"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]

[dependencies]
slog = "*"
slog-term = "*"
slog-scope = "*"
slog-stream = "*"
slog-json = "*"
error-chain = "*"
xcb = "*"
