[project]

name = "xr3wm"
version = "0.0.1"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]
build = "build.rs"

[dependencies.xlib]
git = "https://github.com/tsurai/rust-xlib.git"

[[bin]]
name = "xr3wm"