[package]
name = "xr3wm"
version = "0.1.0"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]

[dependencies]
log = "*"
fern = "*"
error-chain = "*"

[dependencies.xcb]
version = "*"
features = ["xkb"]
