[project]
name = "xr3wm"
version = "0.0.1"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]
build = "build.rs"

[dependencies]
libc = "*"
log = "*"
env_logger = "*"
dylib = "*"

[dependencies.xlib]
git = "https://github.com/Kintaro/rust-xlib.git"
branch = "wtftw"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[lib]
name = "xr3wm"
path = "src/core.rs"

[[bin]]
name = "xr3wm"
path = "src/xr3wm.rs"
