[project]

name = "xr3wm"
version = "0.0.1"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]
build = "build.rs"

[dependencies.xlib]
git = "https://github.com/Kintaro/rust-xlib.git"
branch = "wtftw"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[[bin]]
name = "xr3wm"

